monstersT = {
    ['Headless Fear omfg lul'] = {
        iceRes = 10,
        holyRes = 0,
        physicalRes = 10,
        armor = 35,
        deathRes = 50,
        energyRes = 15,
        fireRes = 0,
        earthRes = 0,
        defence = 35,
    },
    ['Demon'] = {
        iceRes = -10,
        holyRes = -10,
        physicalRes = 30,
        armor = 55,
        deathRes = 30,
        energyRes = 50,
        fireRes = 0,
        earthRes = 40,
        defence = 55,
    },
    ['White Ninja'] = {
        iceRes = 0,
        holyRes = 0,
        physicalRes = -5,
        armor = 15,
        deathRes = -5,
        energyRes = 0,
        fireRes = 0,
        earthRes = 0,
        defence = 37,
    },
}