dofile('data/items/itemSystem.lua')
dofile('data/items/items_functions.lua')

--[[ itemsConf_itemStatT
    [STR] = {                   stat
        fullName = STR          stat name displayed
        extraInfo = STR         displayed extra text
        percent = false         places % symbol for value
        randomStat = INT or 0   how much can itm stat can go negative or positive when randomised or upgraded
    }
]]

--[[ setItemTable config guide
    [STR] = {               setName
        sv = INT            storage value what holds the amount of set items equipped
        setItems = {INT}    list of itemID's which belong to that set
        stats = {
            [INT] = {       amount of set items required
                same as itemTable attribute guide | expect setDSV and spellBuffs
            }
        }
        -- name = STR       setName
    }

]]

--[[ itemTable config guide
    [STR] = {                           slot position name
        [INT] = {                       itemID
            breakchance = INT           for projectiles
            damType = STR or PHSYICAL   combat damage type if its a weapon
            range = INT                 if weapon then DEFAULT wand = 4; range = 3; or 1
            fe = INT                    flying effect
            me = INT                    magic effect
            isWand = BOOL               DEFAULT damType == "spectrum"
            room = INT                  how much room bag has if it is a bag
            requiredTokens = INT or 2   how much tokens requirs to improve stats
            itemAID = INT               if it should have specific itemAID
            onUseFunc = STR             _G[STR](player, item, itemEx, ...) | works with itemAID
            stepInFunc = STR            _G[STR](player, item, _, ...) | works with itemID
            noFullInfo = false          if true then doesnt have detailed view
            
            setDSV = {                  dynamical storage value what is set on item first time its read
                                        onEquip changes storage values based on what is writen on item
                                        onDeEquip sets written storage values on items to -1
                [SV] = {                item:setText("SV"..SV, math.random(min, max))
                    min = INT,          
                    max = INT,          max value should have the value what is the best for item
                },
            },
            spellBuffs = {              registers tables in spellBuffs which is used for spellBook calculations
                [STR] = {               buffName
                    func = STR          functionName with params: Example: "green_powderDamage(player, amount, damType, onlyCheck)"
                                        amount == number, usually formula calculation
                    text = STR          when function RETURNS true or value what is > 0 then RETURNS the text
                                        "EXTRA" is replaced with RETURN value from function
                                        "BONUS" is replaced with secondary RETURN value
                    replace = INT       overwrites the effect text to specific table position, effecT[INT]. Usually used to overwrite default spell information
                    negative = false    if true then allows negative return values from function
                }
            },
            desc = {STR}                item custom description | SV'INT will be replaced with value written on itemText SV'INT(value)
            setSV = {[SV] = INT}        SV = storage value what onEquip is set to INT and onDeEquip is set to -1
            equipFunc = {STR}           extra functions what activate onEquip
            deEquipFunc = {STR}         extra functions what activate onDeEquip
            -- itemID = INT             same as table key
        }
    }
]]

allWeapons = {}
allBoots = {}
allLegs = {}
allBodies = {}
allShields = {}
allQuivers = {}
allHeads = {}
allNormalBags = {}

itemsConf_itemStatT = {
    weight  = {fullName = "Weight",   extraInfo = " (how much the item takes cap)"},
    def     = {fullName = "Defence",  extraInfo = " (reduces damage by value)", randomStat = 1},
    armor   = {fullName = "Armor",    extraInfo = " (armor has chance to reduce physical damage by value)", randomStat = 5},
    barrier = {fullName = "Barrier",  extraInfo = " (blocks damage)"},
    speed   = {fullName = "Movement speed", extraInfo = " (changes player moving speed from tile to tile)", randomStat = 5},
    minDam  = {fullName = "Minimum damage", extraInfo = " (lowest weapon hit)", randomStat = 20},
    maxDam  = {fullName = "Maximum damage", extraInfo = " (highest weapon hit)", randomStat = 20},
    weaponSpeed = {fullName = "Weapon speed", extraInfo = " (interval between hits in milliseconds)"},
    breakchance = {fullName = "Break chance", extraInfo = " (% chance to loose ammo every time its shot or thrown)", percent = true},
    
    energyRes   = {fullName = "Energy resistance",    percent = true, randomStat = 3},
    fireRes     = {fullName = "Fire resistance",      percent = true, randomStat = 3},
    iceRes      = {fullName = "Ice resistance",       percent = true, randomStat = 3},
    deathRes    = {fullName = "Death resistance",     percent = true, randomStat = 3},
    earthRes    = {fullName = "Earth resistance",     percent = true, randomStat = 3},
    physicalRes = {fullName = "Physical resistance",  percent = true, randomStat = 3},
    holyRes     = {fullName = "Holy resistance",      percent = true, randomStat = 3},
    waterRes    = {fullName = "Water resistance",     percent = true, randomStat = 3},
    pvpRes      = {fullName = "PvP resistance",       extraInfo = " (players deal % less damage to you)", percent = true},
    dragonRes   = {fullName = "Dragon resistance",    extraInfo = " (dragon type monsters deal % less damage to you)", percent = true, randomStat = 3},
    beastRes    = {fullName = "Beast resistance",     extraInfo = " (beast type monsters deal % less damage to you)",  percent = true, randomStat = 3},
    undeadRes   = {fullName = "Undead resistance",    extraInfo = " (undead type monsters deal % less damage to you)", percent = true, randomStat = 3},
    slowRes     = {fullName = "Slow resistance",      extraInfo = " (reduces the strength of slow by %)", percent = true, randomStat = 5},
    silenceRes  = {fullName = "Silence resistance",   extraInfo = " (reduces the cooldown length by %)",  percent = true, randomStat = 5},
    stunRes = {
        fullName = "Stun resistance",
        extraInfo = " (Reduces the length of stun duration by %. If stun level too high resistance wont work. 100% = lvl 1; 200% = lvl 2 etc)",
        percent = true,
        randomStat = 5,
    },
    
    mL  = {fullName = "Magic level",            extraInfo = " (changes spell values)"},
    sL  = {fullName = "Shielding skill",        extraInfo = " (changes spell values)"},
    wL  = {fullName = "Weapon skill",           extraInfo = " (changes spell values)"},
    dL  = {fullName = "Distance skill",         extraInfo = " (changes spell values)"},
    sLf = {fullName = "Handcombat skill",       extraInfo = " (changes spell values)"},
    cbv = {fullName = "Critical block value",   extraInfo = " (gives % chance to double the def value)", percent = true, randomStat = 5},
    ccv = {fullName = "Critical hit value",     extraInfo = " (gives % chance to double the damage output)", percent = true, randomStat = 5},
    cH  = {fullName = "Critical heal value",    extraInfo = " (gives % chance to double the spell healing value you make)", percent = true, randomStat = 5},
}

setItemTable = {
    ["fur set"] = {
        sv = SV.furSet,
        setItems = {7457, 7458, 7463, 7464, 7343, 7342},
        stats = {
            [2] = {
                iceRes = 2,
                fireRes = 3,
                armor = 1,
                beastRes = 3,
            },
            [3] = {
                desc = {"[adds 20% drop chance to animal leather]"},
                setSV = {[SV.furSetAnimalLeather] = 20},
                iceRes = 2,
                fireRes = 3,
                armor = 2,
                beastRes = 3,
            },
            [4] = {
                desc = {"[adds 20% drop chance to thick fur and wolf fur]"},
                setSV = {[SV.furSetFurItems] = 20},
                iceRes = 2,
                fireRes = 3,
                armor = 2,
                beastRes = 3,
            },
            [5] = {
                desc = {"[adds 20% drop chance to 'paw' items]"},
                setSV = {[SV.furSetPawItems] = 20},
                iceRes = 3,
                fireRes = 5,
                armor = 3,
                deathRes = 2,
                physicalRes = 1,
                beastRes = 3,
            },
        }
    },
    ["leather set"] = {
        sv = SV.leatherSet,
        setItems = {2467, 2461, 2643, 2649, 11242, 11241, 20109},
        stats = {
            [2] = {
                speed = 13,
            },
            [3] = {
                speed = 13,
                energyRes = 2,
                earthRes = 1,
                deathRes = -2,
                stunRes = 30,
            },
            [4] = {
                speed = 13,
                energyRes = 2,
                earthRes = 1,
                deathRes = -8,
                slowRes = 10,
                stunRes = 50,
            },
            [5] = {
                desc = {"[your attack speed is increased by the amount of movement speed you have]"},
                setSV = {[SV.leatherSetAS] = 1},
                speed = 13,
                energyRes = 2,
                earthRes = 1,
                deathRes = -20,
                slowRes = 10,
                stunRes = 20,
            },
        }
    }
}

itemTable = {
    ["head"] = {
        [3972] = {
            name = "Snaipa helmet",
            desc = {"[!volley deals SV"..SV.snaipaHelmet.."% more damage]", "[adds SV"..SV.snaipaHelmet_breakChance.."% to arrow break chance]"},
            setDSV = {
                [SV.snaipaHelmet] = {min = 20, max = 40, name = "volley damage"},
                [SV.snaipaHelmet_breakChance] = {min = 6, max = 3, name = "break chance"},
            },
            spellBuffs = {
                ["snaipaHelmet"] = {func = "snaipaHelmet(player, amount, onlyCheck)", text = "Snaipa Helmet increased arrow damage by EXTRA"},
                ["snaipaHelmetBreak"] = {func = "snaipaHelmet_breakChance(player)", text = "Snaipa Helmet increased arrow break chance by EXTRA%"},
            },
            armor = 18,
            weight = 7500,
            beastRes = 10,
            earthRes = 10,
            fireRes = -10,
            dL = 3,
        },
        [6433] = {
            name = "Kamikaze mask",
            desc = {
                "[barrier explosion deals SV"..SV.kamikazeMask_explosionDam.."% of total barrier as death damage to surrounding creatures]",
                "[SV"..SV.kamikazeMask.."% of barrier damage goes to death resistance for 10 seconds]",
            },
            setDSV = {
                [SV.kamikazeMask_explosionDam] = {min = 75, max = 100, name = "barrier explosion damage"},
                [SV.kamikazeMask] = {min = 1, max = 3, name = "damage to resistance"},
            },
            requiredTokens = 3,
            armor = 14,
            weight = 6500,
            undeadRes = 10,
            deathRes = 6,
            fireRes = -19,
            iceRes = 12,
            sL = 3,
        },
        [7903] = {
            name = "Pinpua hood",
            desc = {"[Your critical heal chance is increased by SV"..SV.pinpuaHood.."% of your current crit heal]"},
            setDSV = {[SV.pinpuaHood] = {min = 40, max = 60, name = "critical heal improvement"}},
            armor = 15,
            weight = 6000,
            deathRes = 7,
            undeadRes = 9,
            iceRes = 6,
            fireRes = -17,
            earthRes = 15,
            energyRes = -11,
            sL = 2,
            mL = 1,
        },
        [2481] = {
            name = "Warrior helmet",
            desc = {"[strike spell cleaves]"},
            spellBuffs = {["warriorHelmet"] = {func = "warriorHelmet(player, frontPos, amount, onlyCheck)", text = "Deals damage in wider area front of you (Warrior helmet)", replace = 1}},
            setSV = {[SV.warriorHelmet] = 1},
            armor = 22,
            weight = 11000,
            deathRes = 6,
            undeadRes = 12,
            iceRes = 7,
            fireRes = 7,
            earthRes = 5,
            physicalRes = 3,
            energyRes = -12,
            speed = -18,
            wL = 2,
        },
        [18398] = {
            name = "Blessed hood",
            desc = {"[every time you cast spell deal SV"..SV.blessedHood.."% more damage with weapons for 6 seconds. stacks up to 10%]"},
            setDSV = {[SV.blessedHood] = {min = 1, max = 4, name = "weapon damage on proc"}},
            spellBuffs = {
                ["blessedHood_cast"] = {func = "blessedHoodOnCast(player, onlyCheck)", text = "When casted, incrases weapon damage by EXTRA% for 6 seconds. stacks up to 10% (Blessed hood)"},
                ["blessedHood_damage"] = {func = "blessedHood(player, amount)", text = "Blessed hood increased damage by EXTRA"},
            },
            requiredTokens = 3,
            armor = 16,
            weight = 7000,
            deathRes = 6,
            physicalRes = 1,
            iceRes = -10,
            fireRes = -5,
            undeadRes = 5,
            wL = 2,
            dL = 2,
        },
        [12442] = {
            name = "Blessed turban",
            desc = {"[every time you cast spell deal SV"..SV.blessedTurban.."% more damage with spells for 4 seconds. stacks up to 20%]"},
            setDSV = {[SV.blessedTurban] = {min = 1, max = 4, name = "spell damage on proc"}},
            spellBuffs = {
                ["blessedTurban_cast"] = {func = "blessedTurban(player, onlyCheck)", text = "When casted, incrases spell damage by EXTRA% for 4 seconds. stacks up to 20% (Blessed turban)"},
                ["blessedTurban_damage"] = {func = "blessedTurban_damage(player, amount)", text = "Blessed turban increases damage by EXTRA%"},
            },
            requiredTokens = 3,
            armor = 4,
            weight = 5000,
            deathRes = 17,
            physicalRes = -3,
            iceRes = -25,
            fireRes = 11,
            undeadRes = 5,
            mL = 2,
        },
        [9735] = {
            name = "Blessed iron helmet",
            desc = {"[every time you cast spell get SV"..SV.blessedIronHelmet.." armor for 5 seconds. stacks up to 30 armor]"},
            setDSV = {[SV.blessedIronHelmet] = {min = 3, max = 6, name = "armor on proc", afterValueStr = ""}},
            spellBuffs = {
                ["blessedIronHelmet_cast"] = {func = "blessedIronHelmet(player, onlyCheck)", text = "When casted, incrases your armor by EXTRA for 5 seconds. stacks up to 30 (Blessed iron helmet)"},
            },
            requiredTokens = 3,
            armor = 25,
            weight = 10000,
            deathRes = 8,
            iceRes = -15,
            fireRes = -10,
            undeadRes = 5,
            sL = 2,
        },
        [10570] = {
            name = "Amanita hat",
            desc = {"[death damage adds SV"..SV.amanitaHat.."% life back from damage done]"},
            setDSV = {[SV.amanitaHat] = {min = 2, max = 4, name = "life steal"}},
            spellBuffs = {["amanitaHat"]  = {func = "amanitaHat(player, amount, damType, origin, onlyCheck)", text = "Heals EXTRA% from damage done (Amanita hat)"}},
            requiredTokens = 4,
            armor = 8,
            weight = 5500,
            energyRes = 2,
            deathRes = 9,
            undeadRes = 7,
            iceRes = -10,
            fireRes = -20,
            mL = 2,
        },
        [2662] = {
            name = "Arogja hat",
            desc = {"[when barrier breaks, heal yourself SV"..SV.arogjaHat.."% of that barrier value]"},
            setDSV = {[SV.arogjaHat] = {min = 20, max = 40, name = "heal amount on barrier breakdown"}},
            spellBuffs = {["arogjaHat"] = {func = "arogjaHat_heal(player, onlyCheck)", text = "EXTRA% of total barrier amount is healed on breakdown (Arogja hat)"}},
            armor = 7,
            weight = 6000,
            energyRes = 5,
            deathRes = 4,
            iceRes = -12,
            mL = 1,
        },
        [12434] = {
            name = "Hood of natural talent",
            desc = {"[For every 2nd shielding skill point you loose 1 shielding level]"},
            equipFunc = "equipHoodOfNaturalTalent",
            deEquipFunc = "removeHoodOfNaturalTalent",
            armor = 20,
            weight = 5000,
            earthRes = 10,
            sL = 5,
        },
        [2663] = {
            name = "Zvoid turban",
            desc = {"[Increase player max cap by 120% of equipped shield weight]"},
            equipFunc = "equipZvoidTurban",
            deEquipFunc = "removeZvoidTurban",
            armor = 18,
            weight = 13000,
            energyRes = 12,
            physicalRes = -8,
            sL = 1,
        },
        [2461] = {
            name = "Leather helmet",
            setName = "leather set",
            armor = 7,
            weight = 4000,
            speed = 7,
            energyRes = 4,
            deathRes = -12,
        },
        [7458] = {
            name = "Fur cap",
            setName = "fur set",
            armor = 14,
            weight = 6000,
            beastRes = 4,
            fireRes = -18,
            iceRes = 8,
        },
    },
    ["quiver"] = {
        [15481] = {
            name = "Traptrix quiver",
            desc = {"[when someone gets caught in trap, refund SV"..SV.traptrixQuiver.."% of !trap mana]", "[reduces ammo break chance by SV"..SV.quiverBreakChance.."%]"},
            setDSV = {
                [SV.traptrixQuiver] = {min = 30, max = 60, name = "mana refund"},
                [SV.quiverBreakChance] = {min = 3, max = 6, name = "break chance"},
            },
            spellBuffs = {["traptrixQuiver"] = {func = "traptrixQuiver(player, onlyCheck)", text = "When someone gets caught in trap, refund EXTRA% !trap mana (Traptrix quiver)"}},
            weight = 11000,
            earthRes = 12,
            undeadRes = 6,
            deathRes = 6,
            dL = 3,
        },
        [12425] = {
            name = "Fire quiver",
            desc = {"[reduces ammo break chance by SV"..SV.quiverBreakChance.."%]", "[your arrows deal extra SV"..SV.fireQuiverDamage.."% fire damage]"},
            setDSV = {
                [SV.quiverBreakChance] = {min = 5, max = 8, name = "break chance"},
                [SV.fireQuiverDamage] = {min = 8, max = 15, name = "extra fire damage"},
            },
            spellBuffs = {["fireQuiverDamage"] = {func = "fireQuiverDamage(player, target, amount, onlyCheck)", text = "Deals additonal ~EXTRA fire damage (Fire quiver)"}},
            requiredTokens = 3,
            weight = 10000,
            fireRes = 10,
            dL = 2,
        },
    },
    ["shield"] = {
        [6391] = {
            name = "Chokkan",
            desc = {"[You no longer have to face monsters to shoot with range weapons]", "[can equip bow when this shield is equipped]"},
            setSV = {[SV.chokkan] = 1},
            def = 5,
            weight = 13000,
            fireRes = -11,
            earthRes = 11,
            undeadRes = 9,
            deathRes = 9,
            dL = 3,
        },
        [8905] = {
            name = "Supaky",
            desc = {"[!gem-def spells are executed at once with any !gem-def spell activation]"},
            setSV = {[SV.supaky] = 1},
            spellBuffs = {["supaky"] = {func = "supaky(player, res, onlyCheck)", text = "Increases EXTRA resistance against next elemental hit (Supaky shield)", replace = 2}},
            def = 10,
            weight = 15500,
            fireRes = 5,
            earthRes = 5,
            iceRes = 5,
            energyRes = 5,
            sL = 5,
        },
        [2532] = {
            name = "Kodayasu",
            def = 6,
            weight = 11500,
            sL = 3,
            cH = 20,
            fireRes = 5,
            undeadRes = 12,
            physicalRes = 4,
            earthRes = 7,
        },
        [2521] = {
            name = "Akujaaku",
            desc = {"[increases spark and death area by 2]"},
            setSV = {[SV.akujaaku] = 2},
            def = 3,
            weight = 13000,
            energyRes = 10,
            undeadRes = 6,
            deathRes = 10,
            earthRes = -17,
            fireRes = -8,
            mL = 1,
            dL = 1,
        },
        [2520] = {
            name = "Demonic shield",
            desc = {"[Imp increases your spell damage by additional SV"..SV.demonicShield.."%]"},
            setDSV = {[SV.demonicShield] = {min = 5, max = 15, name = "spell damage from imp"}},
            spellBuffs = {["demonicShield"] = {func = "demonicShield(player)", text = "Imp increases your spell damage by additional EXTRA% (Demonic shield)"}},
            def = 6,
            weight = 12000,
            fireRes = 14,
            iceRes = -30,
            undeadRes = 15,
            deathRes = 6,
            mL = 3,
        },
        [2537] = {
            name = "Yashimaki",
            desc = {"[mend spell heals 1 extra area]", "[healing spells give extra armor for 10 seconds]"},
            setSV = {[SV.yashimaki_area] = 1},
            spellBuffs = {["yashimaki"] = {func = "yashimaki(player, target, onlyCheck)", text = "Healed target armor is increased by EXTRA for 10 seconds (Yashimaki shield)"}},
            def = 7,
            weight = 13500,
            iceRes = 12,
            fireRes = -11,
            deathRes = 3,
            undeadRes = 10,
            physicalRes = 2,
            earthRes = 9,
            sL = 2,
        },
        [18410] = {
            name = "Ghatitk shield",
            desc = {"[while !gem-def spell is activated you deal SV"..SV.ghatitkShield.."% more damage with that elemental]"},
            setDSV = {[SV.ghatitkShield] = {min = 10, max = 25, name = "elemental damage"}},
            spellBuffs = {["ghatitkShield"] = {func = "ghatitkShield(player, amount, damType, onlyCheck)", text = "While spell is active you deal EXTRA (Ghatitk shield)"}},
            def = 9,
            weight = 15500,
            energyRes = 12,
            fireRes = -6,
            iceRes = -9,
            earthRes = -12,
            deathRes = 6,
            undeadRes = 14,
            sL = 4,
            wL = 1,
        },
        [8707] = {
            name = "Thunder book",
            desc = {"[increases elemental spell damage SV"..SV.thunderBook.."%]"},
            setDSV = {[SV.thunderBook] = {min = 10, max = 25, name = "elemental damage"}},
            spellBuffs = {["thunderBook"] = {func = "thunderBook(player, amount)", text = "Damage increased by EXTRA (Thunder book)"}},
            requiredTokens = 3,
            def = 2,
            weight = 10000,
            energyRes = 20,
            iceRes = -5,
            fireRes = -5,
            mL = 2,
            sL = 2,
        },
        [2542] = {
            name = "Zvoid shield",
            desc = {"[your resistance spells give +SV"..SV.zvoidShield.."% more resistance]"},
            setDSV = {[SV.zvoidShield] = {min = 10, max = 20, name = "resistance buff"}},
            spellBuffs = {["zvoidShield"] = {func = "zvoidShield(player)", text = "EXTRA% resistance added from Zvoid shield"}},
            def = 6,
            weight = 20000,
            energyRes = 10,
            deathRes = 5,
            iceRes = -20,
            mL = 1,
            wL = -1,
            sL = 3,
        },
        [8909] = {
            name = "Gribit shield",
            desc = {"[buff spell goes to all players around you]"},
            setSV = {[SV.gribitShield] = 1},
            spellBuffs = {
                ["gribitShield"] = {func = "gribitShield(player, buff, duration, areaT, onlyCheck)", text = "Gives protection buff to nearby allies and you for 1 hour (Gribit shield)", replace = 1},
            },
            def = 4,
            weight = 15000,
            earthRes = 14,
            fireRes = -22,
            sL = 2,
        },
        [2522] = {
            name = "Bianhuren",
            desc = {"[Your next !buff spell will reflect physical damage instead of reducing damage, but duration is reduced by 30 minutes]"},
            setSV = {[SV.bianhuren] = 1},
            spellBuffs = {
                ["bianhurenShield"] = {func = "bianhurenActivate(player, amount, duration, onlyCheck)", text = "Reflects EXTRA% physical damage back to attacker (Bianhuren Shield)", replace = 1},
            },
            def = 7,
            weight = 20000,
            earthRes = 14,
            fireRes = 12,
            deathRes = 16,
            iceRes = 10,
            energyRes = 5,
            physicalRes = 3,
            beastRes = 15,
            sL = 4,
        },
        [15491] = {
            name = "Stone shield",
            desc = {"[While !armorup is active and you take total SV"..SV.stoneShield.." damage, refund !armorup manacost on breakdown]"},
            setDSV = {[SV.stoneShield] = {min = 60, max = 40, name = "damage required to proc", afterValueStr = ""}},
            spellBuffs = {["stoneShield"] = {func = "stoneShield(player, damage, onlyCheck)", text = "Taking total EXTRA damage in armorUp state refunds manacost on breakdown (Stone shield)"}},
            def = 11,
            weight = 19000,
            physicalRes = 4,
            iceRes = -22,
            fireRes = -12,
            sL = 3,
        },
        [16103] = {
            name = "Shikara Nankan",
            desc = {"[armor is increased by SV"..SV.shikaraNankan.."% of barrier]"},
            setDSV = {[SV.shikaraNankan] = {min = 3, max = 6, name = "armor buff"}},
            requiredTokens = 3,
            def = 4,
            weight = 12000,
            energyRes = 16,
            earthRes = 8,
            sL = 3,
        },
    },
    ["body"] = {
        [9776] = {
            name = "Goddess armor",
            desc = {"[healing spells remove root and bind effects]"},
            setSV = {[SV.goddessArmor] = 1},
            spellBuffs = {["goddessArmor"] = {func = "goddessArmor(player, nil, onlyCheck)", text = "Removes root and bind effects (Goddess armor)"}},
            armor = 30,
            weight = 16000,
            fireRes = 5,
            undeadRes = 10,
            deathRes = 10,
            sL = 2,
        },
        [11425] = {
            name = "Bloody shirt",
            desc = {"[!fakedeath regenerates health 20+(mL*SV"..SV.bloodyShirt..") per second]"},
            setDSV = {[SV.bloodyShirt] = {min = 4, max = 6, name = "regenation multiplier", afterValueStr = ""}},
            spellBuffs = {["bloodyShirt"] = {func = "bloodyShirt(player, onlyCheck)", text = "Gain EXTRA health per second while faking death (Bloody shirt)"}},
            requiredTokens = 3,
            armor = 5,
            weight = 5000,
            physicalRes = -3,
            mL = 1,
            sL = -1,
        },
        [20109] = {
            name = "Leather vest",
            desc = {"[!throwaxe spell bounces extra SV"..SV.leatherVest.." more times to different target]"},
            setDSV = {[SV.leatherVest] = {min = 1, max = 3, name = "axe bounce amount", afterValueStr = ""}},
            spellBuffs = {["leatherVest"] = {func = "leatherVest_extraThrowAxeBounces(player)", text = "Axe bounces extra EXTRA more times to different target (Leather vest)"}},
            setName = "leather set",
            requiredTokens = 4,
            armor = 15,
            weight = 6000,
            physicalRes = 2,
            fireRes = -10,
            dL = 3,
            sL = -1,
        },
        [12431] = {
            name = "Kamikaze mantle",
            desc = {
                "[barrier explosion deals SV"..SV.kamikazeMantle_explosion.."% of total barrier as death damage to surrounding creatures]",
                "[SV"..SV.kamikazeMantle_percent.."% of barrier explosion damage is added to your next death spell damage]",
            },
            setDSV = {
                [SV.kamikazeMantle_explosion] = {min = 75, max = 100, name = "barrier damage"},
                [SV.kamikazeMantle_percent] = {min = 1, max = 3, name = "death damage from explosion"},
            },
            spellBuffs = {["kamikazeMantle"] = {func = "kamikazeMantle_addDamage(player, onlyCheck)", text = "Damage increased by EXTRA (Kamikaze mantle)"}},
            armor = 25,
            weight = 10000,
            energyRes = -20,
            physicalRes = -3,
            iceRes = 11,
            undeadRes = 8,
            deathRes = 12,
            earthRes = 7,
            mL = 3,
        },
        [13559] = {
            name = "Demonic robe",
            desc = {"[while your Imp is below 50%, you will take SV"..SV.demonicRobe.."% less damage from all sources]"},
            setDSV = {[SV.demonicRobe] = {min = 5, max = 12, name = "damage reduction from imp"}},
            spellBuffs = {["demonicRobe"] = {func = "demonicRobe(player, amount, onlyCheck)", text = "While Imp is below 50%, you will take EXTRA% less damage from all sources (Demonic robe)"}},
            armor = 30,
            weight = 12000,
            fireRes = 18,
            iceRes = -23,
            undeadRes = 12,
            deathRes = 4,
            mL = 3,
        },
        [21725] = {
            name = "Phadra robe",
            desc = {"[you can cast innervate to another player]"},
            setSV = {[SV.phadraRobe] = 1},
            spellBuffs = {["phadraRobe"] = {func = "phadraRobe(player)", text = "You can cast innervate to another player !innervate PLAYERNAME (Phadra robe)"}},
            armor = 28,
            weight = 9000,
            energyRes = 9,
            fireRes = -17,
            iceRes = 5,
            earthRes = -10,
            deathRes = 10,
            undeadRes = 4,
            dL = 3,
            cH = 10,
        },
        [18404] = {
            name = "Ghatitk armor",
            desc = {"[!gem-def heal is increased SV"..SV.ghatitkArmor.."%]"},
            setDSV = {[SV.ghatitkArmor] = {min = 75, max = 150, name = "heal amount"}},
            spellBuffs = {["ghatitkArmor"] = {func = "ghatitkArmor(player, healAmount, onlyCheck)", text = "healt gained from proc is increased EXTRA% (Ghatitk armor)"}},
            armor = 35,
            weight = 14500,
            energyRes = 11,
            fireRes = -5,
            iceRes = -8,
            earthRes = -15,
            deathRes = 5,
            undeadRes = 12,
            sL = 3,
        },
        [18399] = {
            name = "Traptrix coat",
            desc = {"[!trap spell places up to 2 additional traps]", "[all traps damage you]"},
            setSV = {[SV.traptrixCoat] = 1},
            spellBuffs = {["traptrixCoat"] = {func = "traptrixCoat(player, onlyCheck)", text = "Trap is also placed on left and right side from you (Traptrix coat)", replace = 3}},
            armor = 33,
            weight = 11500,
            earthRes = 13,
            fireRes = -18,
            deathRes = 4,
            undeadRes = 11,
            beastRes = 16,
            speed = 8,
            sL = 2,
            dL = -2,
        },
        [7463] = {
            name = "Fur cape",
            setName = "fur set",
            armor = 28,
            weight = 12000,
            beastRes = 6,
            fireRes = -24,
            iceRes = 10,
        },
        [2467] = {
            name = "Leather armor",
            setName = "leather set",
            armor = 10,
            weight = 7000,
            speed = 7,
            energyRes = 6,
            deathRes = -18,
        },
        [21692] = {
            name = "Stone armor",
            desc = {"[While armorup is active and you take damage, heal (sL*SV"..SV.stoneArmor.." + 5) health]"},
            setDSV = {[SV.stoneArmor] = {min = 1, max = 3, name = "heal multiplier"}},
            spellBuffs = {["stoneArmor"] = {func = "stoneArmor_heal(player, onlyCheck)", text = "Taking damage while armorUp active heals you for EXTRA health (Stone armor)"}},
            requiredTokens = 3,
            armor = 35,
            weight = 16000,
            physicalRes = 3,
            iceRes = -30,
            fireRes = -16,
            sL = 2,
        },
        [8871] = {
            name = "Precision robe",
            desc = {"[Your spell radius is increased by 1]"},
            setSV = {[SV.precisionRobe] = 1},
            armor = 22,
            weight = 12000,
            energyRes = 8,
            deathRes = 4,
            fireRes = -16,
            iceRes = 4,
            earthRes = -12,
            mL = 1,
        },
        [2508] = {
            name = "Yashiteki",
            desc = {"[mend spell heals 1 extra area]"},
            setSV = {[SV.yashiteki_area] = 1},
            deEquipFunc = "itemYashiteki",
            armor = 27,
            weight = 11000,
            iceRes = 8,
            fireRes = -13,
            deathRes = 4,
            physicalRes = 1,
            earthRes = 12,
        },
    },
    ["legs"] = {
        [2477] = {
            name = "Shimasu legs",
            desc = {"[SV"..SV.shimasuLegs.."% resisted death damage is added to your barrier]"},
            setDSV = {[SV.shimasuLegs] = {min = 75, max = 125, name = "barrier from resisted death damage"}},
            armor = 16,
            weight = 7000,
            energyRes = -10,
            fireRes = -10,
            iceRes = -10,
            deathRes = 12,
            undeadRes = 6,
            physicalRes = 1,
            mL = 1,
            sL = 1,
        },
        [18405] = {
            name = "Ghatitk legs",
            desc = {"[each melee weapon hit increases you resistance of same type as your weapon deals. buff lasts 3 sec and stacks up to SV"..SV.ghatitkLegs.."%]"},
            setDSV = {[SV.ghatitkLegs] = {min = 3, max = 6, name = "max stack", afterValueStr = ""}},
            armor = 23,
            weight = 10000,
            energyRes = 8,
            fireRes = -4,
            iceRes = -6,
            earthRes = -8,
            deathRes = 5,
            undeadRes = 7,
            sL = 2,
            wL = 1,
        },
        [5918] = {
            name = "Kamikaze short pants",
            desc = {"[increase barrier explosion area]"},
            setSV = {[SV.kamikazeShortPants] = 1},
            armor = 10,
            weight = 8000,
            fireRes = -26,
            energyRes = 6,
            deathRes = 5,
            sL = 2,
            wL = 1,
        },
        [7896] = {
            name = "Frizen kilt",
            desc = {"[ice damage slows targets by SV"..SV.frizenKilt.."% of their speed]"},
            setDSV = {[SV.frizenKilt] = {min = 10, max = 25, name = "slow"}},
            spellBuffs = {["frizenKilt"] = {func = "frizenKilt(player, target, damType, origin, onlyCheck)", text = "Slows target by EXTRA% of target speed (Frizen kilt)"}},
            armor = 14,
            weight = 10000,
            physicalRes = -3,
            fireRes = -30,
            iceRes = 20,
            mL = 3,
            wL = -1,
        },
        [2495] = { 
            name = "Demonic legs",
            desc = {"[Imp will have same resistance you had when spell is casted]", "[Imp HP is increased SV"..SV.demonicLegs.."% when spell is casted]"},
            setDSV = {[SV.demonicLegs] = {min = 50, max = 150, name = "imp health incrased on cast"}},
            spellBuffs = {["demonicLegs"] = {func = "demonicLegs(player, imp, onlyCheck)", text = "Imp shares caster base resistances and HP is increased EXTRA% (Demonic legs)]"}},
            armor = 18,
            weight = 7000,
            fireRes = 15,
            iceRes = -26,
            undeadRes = 10,
            deathRes = 2,
            mL = 2,
            sL = 1,
        },
        [2504] = {
            name = "Stone legs",
            desc = {"[While !armorup active, you take SV"..SV.stoneLegs.."% less damage from all sources]"},
            setDSV = {[SV.stoneLegs] = {min = 3, max = 6, name = "damage reduction while !armorup active"}},
            spellBuffs = {["stoneLegs"] = {func = "stoneLegs(player, damage, onlyCheck)", text = "You take EXTRA% less damage from all sources (Stone legs)]"}},
            requiredTokens = 3,
            armor = 29,
            weight = 9000,
            physicalRes = 3,
            iceRes = -15,
            fireRes = -9,
            undeadRes = 15,
            deathRes = 3,
            speed = -10,
            wL = -2,
            sL = 2,
        },
        [18400] = {
            name = "Chamak legs",
            desc = {"[taunted target deals SV"..SV.chamakLegs.."% less damage]"},
            setDSV = {[SV.chamakLegs] = {min = 10, max = 20, name = "damage reduction on taunted target"}},
            spellBuffs = {["chamakLegs"] = {func = "chamakLegs(player, target, damage, onlyCheck)", text = "Reduces target damage by EXTRA% (Chamak legs)"}},
            armor = 16,
            weight = 6500,
            earthRes = 10,
            fireRes = -12,
            deathRes = 3,
            undeadRes = 10,
            beastRes = 13,
            speed = 15,
            dL = 1,
            sL = 1,
        },
        [2507] = {
            name = "Gribit legs",
            desc = {"[when gribit shield equipped, other players in party and 5 or less tiles away from you with !buff get SV"..SV.gribitLegs.."% earth resistance]"},
            setDSV = {[SV.gribitLegs] = {min = 20, max = 40, name = "earth resistance from !buff"}},
            spellBuffs = {["gribitLegs"] = {func = "gribitLegs(player, damType, onlyCheck)", text = "Nearby players in party with !buff get EXTRA% earth resistance (Gribit legs)"}},
            armor = 25,
            weight = 7500,
            earthRes = -60,
            mL = 2,
            sL = 2,
        },
        [7464] = {
            name = "Fur shorts",
            setName = "fur set",
            armor = 21,
            weight = 9000,
            beastRes = 5,
            fireRes = -18,
            iceRes = 8,
        },
        [3983] = {
            name = "Speedzy legs",
            desc = {"[gain movement speed for SV"..SV.speedzyLegs_duration.." seconds each time you get healed]"},
            setDSV = {[SV.speedzyLegs_duration] = {min = 4, max = 6, name = "speed duration", afterValueStr = " second(s)"}},
            setSV = {[SV.speedzyLegs] = 1},
            spellBuffs = {["speedzyLegs"] = {func = "speedzyLegs(player, onlyCheck)", text = "Healing increases movement speed for EXTRA seconds (Speedzy legs)"}},
            requiredTokens = 3,
            armor = 14,
            weight = 9000,
            fireRes = 8,
            deathRes = -14,
            slowRes = 20,
            mL = 1,
            sL = -1,
            speed = 13,
        },
        [11304] = {
            name = "Genso Fedo",
            desc = {"[heal yourself by SV"..SV.gensoFedo.." and remove (SV"..SV.gensoFedo.."/2) barrier if elemental damage on you doesn't take hp]"},
            setDSV = {[SV.gensoFedo] = {min = 8, max = 12, name = "heal amount", afterValueStr = ""}},
            armor = 26,
            weight = 10000,
            mL = 1,
            energyRes = 16,
            deathRes = 6,
            iceRes = -25,
        },
        [15409] = {
            name = "Intrinsic legs",
            desc = {"[gain 1 mana for resisting SV"..SV.intrinsicLegs.."% elemental damage (max 5 mana)]"},
            setDSV = {[SV.intrinsicLegs] = {min = 50, max = 20, name = "resisance required to proc"}},
            armor = 20,
            weight = 8000,
            fireRes = 5,
            iceRes = 5,
            earthRes = -20,
            deathRes = 5,
            energyRes = 5,
            wL = -1,
            sL = 1,
        },
        [2649] = {
            name = "Leather legs",
            setName = "leather set",
            armor = 12,
            weight = 7000,
            speed = 10,
            energyRes = 5,
            deathRes = -15,
        },
        [7730] = {
            name = "Kamikaze pants",
            desc = {"[barrier explodes on breakdown]", "[barrier explosion deals SV"..SV.kamikazePants_explosion.."% of total barrier as death damage to surrounding creatures]"},
            setDSV = {[SV.kamikazePants_explosion] = {min = 75, max = 100, name = "barrier damage"}},
            spellBuffs = {["kamikazePants"] = {func = "kamikazePants_explosionPercent(player)", text = "When barrier runs out it explodes with death damage (Kamikaze pants)"}},
            armor = 18,
            weight = 8000,
            undeadRes = 6,
            deathRes = 10,
            energyRes = 12,
            fireRes = -16,
            iceRes = 8,
            sL = 2,
        },
    },
    ["boots"] = {
        [23540] = {
            name = "Chivit boots",
            desc = {"[if your hp is below 25% then you get SV"..SV.chivitBoots.."% critical hit chance for your weapon hits]"},
            setDSV = {[SV.chivitBoots] = {min = 15, max = 25, name = "crit chance when below 25% HP"}},
            requiredTokens = 3,
            armor = 14,
            weight = 7000,
            deathRes = 12,
            speed = 22,
            wL = 2,
            dL = 2,
        },
        [11303] = {
            name = "Kakki boots",
            desc = {"[if your mana is below 25% then you take SV"..SV.kakkiBoots.."% less damage from all sources]"},
            setDSV = {[SV.kakkiBoots] = {min = 6, max = 15, name = "damage reduction when below 25% HP"}},
            requiredTokens = 4,
            armor = 10,
            weight = 5500,
            deathRes = 10,
            speed = 25,
            mL = 2,
            sL = 2,
        },
        [11117] = {
            name = "Zvoid boots",
            desc = {"[if your char pays more than SV"..SV.zvoidBoots_mana.." mana then, next non magic weapon hit deals up to extra (SV"..SV.zvoidBoots_damage.."*10) energy damage]"}, 
            setDSV = {
                [SV.zvoidBoots_mana] = {min = 25, max = 20, name = "mana required to proc", afterValueStr = ""},
                [SV.zvoidBoots_damage] = {min = 20, max = 30, name = "maximum damage multiplier on proc", afterValueStr = ""},
            },
            spellBuffs = {["zvoidBoots"] = {func = "zvoidBoots_mana(player, manaCost, onlyCheck)", text = "Next non magic weapon hit deals up to EXTRA extra energy damage (Zvoid boots)"}},
            requiredTokens = 3,
            armor = 12,
            weight = 5000,
            energyRes = 12,
            iceRes = 7,
            fireRes = 10,
            deathRes = -5,
            speed = 15,
            mL = 1,
            sL = 1,
        },
        [7893] = {
            name = "Arcane boots",
            desc = {"[if your char pays less than SV"..SV.arcaneBoots_mana.." mana then, next non magic weapon hit deals up to extra (SV"..SV.arcaneBoots_damage.."*10) energy damage]"},
            setDSV = {
                [SV.arcaneBoots_mana] = {min = 7, max = 10, name = "mana required to proc", afterValueStr = ""},
                [SV.arcaneBoots_damage] = {min = 10, max = 20, name = "maximum damage multiplier on proc", afterValueStr = ""},
            },
            spellBuffs = {["arcaneBoots"] = {func = "arcaneBoots_mana(player, manaCost, onlyCheck)", text = "Next non magic weapon hit deals up to EXTRA extra energy damage (Arcane boots)"}},
            requiredTokens = 3,
            armor = 6,
            weight = 6000,
            energyRes = 10,
            iceRes = 5,
            fireRes = 8,
            deathRes = -10,
            speed = 20,
            mL = 1,
            wL = 1,
        },
        [7457] = {
            name = "Fur boots",
            setName = "fur set",
            armor = 10,
            weight = 4000,
            beastRes = 4,
            fireRes = -15,
            iceRes = 5,
            speed = 10,
        },
        [2643] = {
            name = "leather boots",
            setName = "leather set",
            armor = 5,
            weight = 3000,
            energyRes = 2,
            deathRes = -6,
            speed = 16,
        },
        [2645] = {
            name = "Warrior boots",
            desc = {"[strike spell cost SV"..SV.warriorBoots.." mana (cant be modified)]"},
            setDSV = {[SV.warriorBoots] = {min = 3, max = 1, name = "strike spell mana cost"}},
            spellBuffs = {["warriorBoots"] = {func = "warriorBoots(player, spellName)", text = "Manacost is set to EXTRA and can't be modified (Warrior boots)"}},
            requiredTokens = 4,
            armor = 14,
            weight = 5500,
            deathRes = 12,
            undeadRes = 10,
            iceRes = 6,
            fireRes = 6,
            earthRes = 4,
            physicalRes = 2,
            energyRes = -10,
            speed = -20,
        },
        [18406] = {
            name = "The Nami boots",
            desc = {"[some spells deal their effects when they pass trough creatures]", "[improves death and spark radius by 2]"},
            setSV = {[SV.namiBoots] = 2},
            spellBuffs = {
                ["namiBootsBuff_taunt"] = {func = "namiBoots_equipped(player)", text = "everyone on the spell path gets taunted (the nami boots)"},
                ["namiBootsBuff_volley"] = {func = "namiBoots_equipped(player)", text = "Arrows which reach maximum distance deal damage to creatures they pass (The Nami boots)"},
                ["namiBootsBuff_heat"] = {func = "namiBoots_equipped(player)", text = "deals fire damage to all creatures the spell passes trough (The Nami boots)"},
                ["namiBootsBuff_shiver"] = {func = "namiBoots_equipped(player)", text = "deals ice damage to all creatures the spell passes trough (The Nami boots)"},
            },
            armor = 4,
            weight = 6000,
            iceRes = 18,
            fireRes = -21,
            earthRes = 6,
            slowRes = 20,
            stunRes = 40,
            physicalRes = -4,
            energyRes = -13,
            speed = 10,
        },
    },
    ["arrows"] = {
        [2544] = {
            name = "Arrow",
            weight = 0,
            minDam = 200,
            maxDam = 260,
            fe = 3,
            me = 1,
            breakchance = 15,
            noFullInfo = true,
            stepInFunc = "pickUpItem",
        },
    },
    ["weapon"] = {
        [2184] = {
            name = "Magic wand",
            desc = {"[Every wand damage type is: Spectrum damage]"},
            damType = "spectrum",
            weight = 15000,
            minDam = 45*5,
            maxDam = 55*5,
            weaponSpeed = 2000,
        },
        [2398] = {
            name = "Mace",
            weight = 16000,
            minDam = 210,
            maxDam = 350,
            weaponSpeed = 2000,
        },
        [2380] = {
            name = "Hand axe",
            weight = 16000,
            minDam = 30,
            maxDam = 530,
            weaponSpeed = 2000,
        },
        [2376] = {
            name = "Sword",
            weight = 15000,
            minDam = 115,
            maxDam = 145,
            weaponSpeed = 1000,
        },
        [2389] = {
            name = "Spear",
            desc = {"[Can not throw spears if have only 1 equipped]"},
            weight = 1000,
            minDam = 80,
            maxDam = 560,
            weaponSpeed = 2000,
            fe = 1,
            me = 1,
            range = 4,
            breakchance = 2,
            noFullInfo = true,
            stepInFunc = "pickUpItem",
        },
        [7367] = {
            name = "Regenative spear",
            desc = {"[You can quickly equip range weapons by using them]", "[This spear appears back in hand after throwing]"},
            weight = 20000,
            minDam = 120,
            maxDam = 150,
            weaponSpeed = 2000,
            fe = 18,
            me = 1,
            range = 4,
            breakchance = 0,
        },
        [3965] = {
            name = "Hunting spear",
            desc = {"[deals 10% more damage to slowed targets when thrown]"},
            weight = 1200,
            minDam = 100,
            maxDam = 580,
            weaponSpeed = 2000,
            fe = 17,
            me = 1,
            range = 4,
            breakchance = 2,
            noFullInfo = true,
            stepInFunc = "pickUpItem",
        },
        [2456] = {
            name = "Bow",
            weight = 15000,
            speed = 20,
            minDam = 40,
            maxDam = 60,
            range = 5,
            weaponSpeed = 2000,
            ammo = "arrows",
            blockSlots = "shield",
            blockMsg = "You can not equip bow, because you have shield in other hand",
        },
        [15400] = {
            name = "Yashinuken",
            desc = {"[USE: If you have yashiteki equipped, you can Toggle OFF healing monsters with mend spell]", "[mend spell heals 1 extra area]"},
            setSV = {[SV.yashinuken_area] = 1},
            itemAID = AID.other.yashinuken,
            onUseFunc = "yashinukenWand_onUse",
            deEquipFunc = "itemYashiteki",
            weight = 16000,
            earthRes = 5,
            minDam = 60*5,
            maxDam = 63*5,
            weaponSpeed = 2000,
            mL = 2,
        },
        [2183] = {
            desc = {"[!heat will do additonal SV"..SV.atsuiKori_ice.."% ICE damage]", "[!shiver will do additional SV"..SV.atsuiKori_fire.."% FIRE damage]"},
            name = "Atsui Kori",
            setDSV = {
                [SV.atsuiKori_ice] = {min = 15, max = 25, name = "ice damage"},
                [SV.atsuiKori_fire] = {min = 15, max = 25, name = "fire damage"},
            },
            spellBuffs = {["atsuiKori"] = {func = "atsuiKori(player, target, pos, amount, damType, onlyCheck)", text = "Deals additional EXTRA% BONUS damage (Atsui Kori wand)"}},
            damType = "spectrum",
            weight = 15000,
            fireRes = 3,
            iceRes = 3,
            minDam = 48*5,
            maxDam = 58*5,
            weaponSpeed = 2000,
        },
        [2190] = {
            name = "Kaiju Wall wand",
            desc = {"[gives SV"..SV.kaijuWall.." extra barrier for !barrier spell]"},
            setDSV = {[SV.kaijuWall] = {min = 50, max = 150, name = "barrier amount", afterValueStr = ""}},
            spellBuffs = {["kaijuWall"] = {func = "kaijuWall(player)", text = "Additonal EXTRA barrier comes from (Kaiju Wall wand)"}},
            damType = "spectrum",
            weight = 15000,
            energyRes = 4,
            minDam = 50*5,
            maxDam = 60*5,
            weaponSpeed = 2000
        },
        [15647] = {
            name = "Purifying mallet",
            desc = {"[USE: clear all debuffs and deal holy damage around you, depending on you weapon skill and level, cooldown SV"..SV.purifyingMallet_cd.." seconds]"},
            setDSV = {[SV.purifyingMallet_cd] = {min = 25, max = 60, name = "cooldown reduction", afterValueStr = " second(s)"}},
            itemAID = AID.other.weapon_mallet,
            onUseFunc = "purifyingMallet_onUse",
            requiredTokens = 3,
            weight = 21000,
            minDam = 230,
            maxDam = 390,
            weaponSpeed = 2000,
            physicalRes = 2,
            ccv = 10,
        },
        [13760] = {
            name = "Immortal Kamikaze",
            desc = {"[USE: explode barrier]","[barrier explosion deals SV"..SV.immortalKamikaze_explosion.."% of total barrier as death damage to surrounding creatures]"},
            setDSV = {[SV.immortalKamikaze_explosion] = {min = 150, max = 200, name = "barrier damage"}},
            itemAID = AID.other.kamikaze_wand,
            onUseFunc = "kamikazeWand_onUse",
            damType = "spectrum",
            requiredTokens = 3,
            weight = 16000,
            minDam = 55*5,
            maxDam = 60*5,
            weaponSpeed = 2000,
            deathRes = 6,
            energyRes = 4,
        },
    },
    
    ["bag"] = {
        [1997] = {
            name = "Golden bag",
            weight = 18000,
            room = 10,
            fireRes = 5,
            energyRes = -10,
        },
        [7343] = {
            name = "Fur bag",
            desc = {"[Doubles the 'Paw' drop chance]"},
            setName = "fur set",
            weight = 14000,
            room = 8,
            iceRes = 8,
            fireRes = -12,
        },
        [7342] = {
            name = "Fur backpack",
            desc = {"[Doubles the 'Paw' drop chance]"},
            setName = "fur set",
            weight = 20000,
            room = 12,
            iceRes = 10,
            fireRes = -16,
        },
        [11241] = {
            name = "Leather backpack",
            setName = "leather set",
            weight = 21000,
            room = 13,
            earthRes = 4,
        },
        [11242] = {
            name = "Leather bag",
            setName = "leather set",
            weight = 13000,
            room = 7,
            earthRes = 3,
        },
        [1987] = {name = "Bag", weight = 18000, room = 7},
        [1996] = {name = "Grey bag", weight = 20000, room = 9},
        [1993] = {name = "Red bag", weight = 20000, room = 9},
        [1995] = {name = "Blue bag", weight = 20000, room = 9},
        [1991] = {name = "Green bag", weight = 20000, room = 9},
        [5801] = {name = "Tutorial bag", weight = 10000, room = 4},
        [15645] = {name = "Tutorial bag", weight = 50000, room = 6},
        [10518] = {name = "Tutorial bag", weight = 65000, room = 8},
    },
}

startUpT["items_startUp"] = 1
print("itemSystem loaded..")